### ISSUE TITLE
What is the state of this library?

### ISSUE THREAD

**Issue by pwaterz** [jsteggink/solarium-cloud#2]
What is the state of this library? It says it's not ready for production, would it be possible to outline why?

**Comment by leuchtdiode** [comment]
Any news? Would be interesting for me as well.

I'm using Solarium now to connect to a single node, but want to switch to SolrCloud with as few effort as possible.

**Comment by jsteggink** [comment]
You could use the library, it should word. Thought, I'm not actively developing on this anymore. However, might there be any issues, just let me know and I'll see if I can fix it.
